"""Supported crowdfunding platforms (scraper + discovery UI)."""

PLATFORM_CATALOG: list[dict[str, str]] = [
    {"id": "gofundme", "label": "GoFundMe"},
    {"id": "launchgood", "label": "LaunchGood"},
    {"id": "fundly", "label": "Fundly"},
    {"id": "islamicrelief_ca", "label": "Islamic Relief (Canada)"},
    {"id": "ketto", "label": "Ketto (India)"},
    {"id": "milaap", "label": "Milaap (India)"},
    {"id": "mchanga", "label": "M-Changa (Africa)"},
    {"id": "backabuddy", "label": "BackaBuddy (South Africa)"},
    {"id": "giveasia", "label": "Give.asia (Southeast Asia)"},
    {"id": "thundafund", "label": "Thundafund (Africa)"},
    {"id": "justgiving", "label": "JustGiving"},
    {"id": "gogetfunding", "label": "GoGetFunding"},
    {"id": "givebutter", "label": "Givebutter"},
    {"id": "mightycause", "label": "Mightycause"},
    {"id": "chuffed", "label": "Chuffed"},
    {"id": "fundrazr", "label": "FundRazR"},
    {"id": "globalgiving", "label": "GlobalGiving"},
    {"id": "donorbox", "label": "Donorbox"},
    {"id": "patreon", "label": "Patreon"},
    {"id": "opencollective", "label": "Open Collective"},
    {"id": "impactguru", "label": "ImpactGuru"},
    {"id": "whydonate", "label": "WhyDonate"},
    {"id": "givesendgo", "label": "GiveSendGo"},
    {"id": "givengain", "label": "GivenGain"},
    {"id": "leetchi", "label": "Leetchi"},
    {"id": "freefunder", "label": "FreeFunder"},
    {"id": "plumfund", "label": "Plumfund"},
    {"id": "kofi", "label": "Ko-fi"},
    {"id": "liberapay", "label": "Liberapay"},
    {"id": "helloasso", "label": "HelloAsso (France)"},
    {"id": "betterplace", "label": "Betterplace (Germany)"},
    {"id": "idonate", "label": "iDonate (Ireland)"},
    {"id": "steunactie", "label": "Steunactie (Netherlands)"},
    {"id": "kisskissbankbank", "label": "KissKissBankBank"},
    {"id": "ulule", "label": "Ulule"},
    {"id": "catarse", "label": "Catarse (Brazil)"},
    {"id": "goteo", "label": "Goteo (Spain)"},
    {"id": "vakinha", "label": "Vakinha (Brazil)"},
    {"id": "rally", "label": "Rally.org"},
    {"id": "everyorg", "label": "Every.org"},
]

SUPPORTED_PLATFORM_COUNT = len(PLATFORM_CATALOG)
